version: '3'
services:
  app1:
    build:
      context: ./app1
      dockerfile: Dockerfile
    # ports:
    #   - "3000:80"
      
  app2:
    build:
      context: ./app2
      dockerfile: Dockerfile

    # ports:
    #   - "3001:80"
    
  app3:
    build:
      context: ./app3
    # ports:
    #   - "3002:80"
    
  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile

    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app1
      - app2
      - app3
