version: '3'
services:
  app1:
    build:
      context: ./app1
    ports:
      - "8081:80"
      
  app2:
    build:
      context: ./app2
    ports:
      - "8082:80"
    
  app3:
    build:
      context: ./app3
    ports:
      - "8083:80"
